### ISSUE TITLE
Error while parsing valid ++< sequence

### ISSUE THREAD

**Issue by sinelaw** [jswebtools/language-ecmascript#63]
Example:

    for(var l=1;l++<0;) { }

Resulting error:

> user error ("parse.js" (line 1, column 17):
> unexpected '<'
> expecting end of "++")

**Comment by achudnov** [comment]
Which branches have you tested it with? master? es5?

**Comment by sinelaw** [comment]
Works on es5 branch, doesn't work on hackage version

**Comment by achudnov** [comment]
Thanks. The Hackage version is still legacy code that has a lot of bugs that can't be fixed easily due to limitations of the implementation. The es5 branch is a complete rewrite that avoids these limitations. (It still has a few bugs that I haven't ironed out yet.) So, I won't be fixing any non-trivial bugs for the 0.* versions as they are going to be superseded by the es5 branch (proposed version 5.0.0.0).
